language: python
python:
- 3.6
install:
  - "pip install pipenv"
  - "pipenv install"
  - "pipenv install codecov"
before_script:
- cd mango-api
script:
- python -m unittest discover
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: ZTVKsq4aw3pGMhNpF3qOn0ONn4TD/TSbpcSNXG2U8z1X59wjio3mq2YG6TFAmJyXZOnZ4bLpwgOm/f6nr1U3z+n1RgSaHtX0L9ZbGKmhkDK1xoj+w+mkfIKYHCPCMSYabu2Y3NIix2b6GB5A8EodOS4cpYtHWF+Bt9rb952tFfr+DHNt7p5OrXNzk/KirsRJ33Bgasp9mqULS5DGHreHqZ9XnRZioycsovY3nsOulPv1tT9xezGC8uYBmWY3rjH4vJ4qTcK3V0bBMO1ldyCURSIPu4kXghdLB+DgpHycJUsiaDgoFpzDgc75am2o5Rxz2en3leByIlFqQWgK1eBaDO1CKmi1KzaNP9WTswIF59AQ9g6PbDChAqpwXeQc76/XJc3u/vao6GO8ZncpONSv0myLbfD8yvefybmgSP/ygDS2ClaPpluC0qOlrKbu9cWcOp0lotL9ZqKp4cZVKAtalgAdK3PJec0X++bNSItFsDsSHwfQOFaEEnRDVN9eZSEUUA0n6/XS8zkE8GfUTDoYd+C5tyP7AkveH519HQ0K1r6oKHg3THXg8KVhCbnQq3SbX1cJBhawp6iD5cWoogiv4i8sqVk2E/TjXtkohd7O1cq14pbCym/fe3YdhKmEDPDjvXFOGQzNJgp+fuuey9MWM4euPIE1zHwNHpJOoEx+0JQ=
    app: mango-api-heroku
skip_cleanup: true
