language: python
python:
- 3.6
install:
- pip install pipenv
- pipenv install
before_script:
- cd mango-api
script:
- python -m unittest discover
deploy:
- provider: heroku
  api_key:
    secure: ga2r486l2ZT0br7o2baC8/T9beyIBzI7L7Bc2S+lYXc0ci0p2LFJFghdMEwK8V5R+2LfwOBEcB1/h9FDYz2tiBRq6bDVTEyyL/zME3+eZTnXoim6Kcy2X67cNaOyldgrLUD4pr7S8AzfK2zE781KuLIaM/056e84Ci2BQTK58dqdMRw2OZPZSV2Agqaf7PQlBko1lbGqpmdjojYHyNP1I0urhPK53UXZ7Jy2rnDIhPEVejSR5roDc0SD+lUaef++FC1YMg01L663kzVK00iuwgqbesuAlWbXOirES8sCSdgGZNKQQ2SX/dQ8NLIGvda4mF7IdRqy93hpYw8u8AcdJH4fgSU9NS8ftQugm1Z+VYyLiANqz75oGdvViu3aDki6Mv/B3CFWR5KGUNsNi4dy6VrCiZLLHwbC4fpInIHgKq17qR6H8GTp9CCvgYrEAQfi0ok86TSA0fvJpcr5Va0LIlfquDJKktmimvpUT7gA65E8w931m1i/pVUu6VstanX5GF3+BN+aDGI0HezbPjxovYVJBu7f60X5XQXmgjQjBOn7yDGBAGkm+mr/vRjhwj1Ga3H6C+gsZuS2v83S6KnTldIxKTRA/Yh4dqRdi1+4f2EcI8f1BaZZII5MWlrw5q9oSqGxF/u8eIJXKK0E6BMCQ0ANMnjwQ20LNOsOwaB1MPQ=
  app: mango-api-heroku
  skip_cleanup: true
  on:
    branch: release